# Generated by Django 5.2.17 on 2026-09-12 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ligas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResenaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('puntuacion', models.PositiveSmallIntegerField(default=5)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('publicada', 'Publicada'), ('oculta', 'Oculta')], default='pendiente', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resena',
                'verbose_name_plural': 'Resenas',
                'db_table': 'resenas',
            },
        ),
        migrations.CreateModel(
            name='PartidoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.IntegerField(default=1)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('jugado', 'Jugado'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='programado', max_length=15)),
                ('goles_local', models.IntegerField(blank=True, null=True)),
                ('goles_visitante', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_de_local', to='ligas.equipomodel')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_de_visitante', to='ligas.equipomodel')),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='ligas.estadiomodel')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='ligas.ligamodel')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'db_table': 'partidos',
            },
        ),
    ]
