# Generated by Django 5.2.17 on 2026-09-12 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partidomodel',
            name='programado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_programados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resenamodel',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resenamodel',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='partidos.partidomodel'),
        ),
        migrations.AddConstraint(
            model_name='resenamodel',
            constraint=models.UniqueConstraint(fields=('partido', 'autor'), name='una_resena_por_usuario_y_partido'),
        ),
    ]
