# Generated by Django 5.2.17 on 2026-09-12 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LigaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('temporada', models.CharField(max_length=9)),
                ('pais', models.CharField(max_length=60)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'db_table': 'ligas',
                'unique_together': {('nombre', 'temporada')},
            },
        ),
        migrations.CreateModel(
            name='EquipoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=80)),
                ('fundacion', models.IntegerField()),
                ('escudo_url', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='ligas.ligamodel')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
                'unique_together': {('liga', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='EstadioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('ciudad', models.CharField(max_length=80)),
                ('capacidad', models.IntegerField()),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estadios', to='ligas.equipomodel')),
            ],
            options={
                'verbose_name': 'Estadio',
                'verbose_name_plural': 'Estadios',
                'db_table': 'estadios',
                'unique_together': {('equipo', 'nombre')},
            },
        ),
    ]
