# Generated by Django 5.2.17 on 2026-09-12 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ligas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('abreviatura', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Posicion',
                'verbose_name_plural': 'Posiciones',
                'db_table': 'posiciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='JugadorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('dorsal', models.PositiveSmallIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=60)),
                ('altura_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pie_habil', models.CharField(choices=[('derecho', 'Derecho'), ('izquierdo', 'Izquierdo'), ('ambidiestro', 'Ambidiestro')], default='derecho', max_length=12)),
                ('foto_url', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jugadores', to='ligas.equipomodel')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jugadores', to='jugadores.posicionmodel')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'jugadores',
                'ordering': ['equipo', 'dorsal'],
                'constraints': [models.UniqueConstraint(fields=('equipo', 'dorsal'), name='dorsal_unico_por_equipo')],
            },
        ),
    ]
